// Auto generated by env plugin. DO NOT EDIT.
type Env = {
  AITO_APP_NAME: string;
  AITO_DISPLAY_NAME: string;
  AITO_PRIMARY_COLOR: string;
  AITO_ICON_URL: string;
  AITO_API_BASE_URL: string;
  AITO_STAGE: string;
};

interface ImportMeta {
  readonly env: Env & {};
}
